version: '3'
services:
  nginx:
    build: ./containers/nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usrshare/nginx/
      - ./containers/nginx:/etc/nginx/conf.d
  express:
    build: ./containers/express
    ports:
      - "8000:8000"
    volumes:
      - ./containers/express:/home/app/project
      - ./containers/express/node_modules:/home/app/project/node_modules